# Generated by Django 4.0.7 on 2023-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=10000)),
                ('processed_text', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
