# Generated by Django 4.0.7 on 2023-12-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextData',
        ),
    ]
