# Generated by Django 5.0.1 on 2024-02-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='bot_response',
        ),
    ]
