from django.db import migrations, models
from django.utils.timezone import now, utc  # Import utc explicitly

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),  # Use auto_now_add=True to set the current time automatically
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]

    def generate_created_at(apps, schema_editor):
        Chat = apps.get_model('base', 'Chat')
        for chat in Chat.objects.all():
            chat.created_at = now()
            chat.save()

    # Use this if you need to set the created_at field for existing records
    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.RunPython(generate_created_at),  # RunPython for setting created_at field for existing records
    ]
# Generated by Django 4.0.7 on 2023-12-08 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import now
created_at = now(utc)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 8, 16, 45, 42, 139882, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
