# Generated by Django 4.0.7 on 2023-12-08 16:45

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 8, 16, 45, 42, 139882, tzinfo=pytz.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
